### ISSUE TITLE
Ancestry of MERS-CoV strains from camel host

### ISSUE THREAD

**Issue by MManee** [kacst-bioinfo-lab/labwork#20]
- main reference paper: https://www.nature.com/articles/srep18825.pdf
- we have to replicate selected figures in reference paper 
- replication is essential to check the quality of our pipeline

TO DO
- [x] we have to replicate figure1 and figure 2 using 70 human strains from reference paper
  - accession numbers and sequences in fasta format are located here: https://github.com/kacst-bioinfo-lab/labwork/tree/master/data/shared/mers_cov 
- [x] we have to replicate figure 3 and table 1 for putative recombination regions

**Comment by bioinfo2016** [comment]
To install MAFFT software on the srver:

1- Transfer the source package of MAFFT to a directory on the server. You can the source package  from:
https://mafft.cbrc.jp/alignment/software/installation_without_root.html.

2- Then unzip the package using the following command: 

tar xvf mafft-7.402-without-extensions-src.tar.

3- Edit the first line of Makefile in the 'core' directory as follows:

cd mafft-x.xxx-with-extensions/core/

vi Makefile (any other text editor is ok.)
From:
PREFIX = /usr/local
To:
PREFIX = /home/your_home/somewhere (must be absolute path). For example:/home/shomrani/maff-dir 

4- Also edit the third line of Makefile
From:
BINDIR = $(PREFIX)/bin
To:
BINDIR = /home/your_home/bin.

5- Compile and install.
% make clean
% make
% make install



Note: you do not need root permission.

**Comment by atalgarni** [comment]
https://www.nature.com/articles/emi201789#materials-and-methods

**Comment by bioinfo2016** [comment]
The attached file contains detailed info about experiments have been run by BEAST.

[BEAST log file.pdf](https://github.com/kacst-bioinfo-lab/labwork/files/2524347/BEAST.log.file.pdf)

**Comment by bioinfo2016** [comment]
The attached file contains detailed info about experiments have been run by BEAST.
