### ISSUE TITLE
Identify Camel_TRF

### ISSUE THREAD

**Issue by atalgarni** [kacst-bioinfo-lab/labwork#21]
## Identify Arabian camel tandem repeats

1. Identify Tandem repeat using TRF tool found at https://tandem.bu.edu/trf/trf.download.html

- Run the TRF using default setting:
` trf409.macosx (input genome.fasta) 2 7 7 80 10 50 2000 -d -f -m` or use `-h` instead of `-d` 

2. Clean up the output of TRF tool using perl script found at 
http://archive.gramene.org/db/markers/ssrtool 
or simply copy the following link to download the source code and run it as
 `perl ssr.pl input file(TRF.dat file) > output`
ftp://ftp.gramene.org/pub/gramene/archives/software/scripts/ssr.pl

the files will be added shortly!!!!!

**Comment by MManee** [comment]
- we used perf tool to identify SSR motifs
- the tool seems to work well to identify perfect SSRs [PERF GitHub Page](https://github.com/RKMlab/perf)
