### ISSUE TITLE
Genome-wide Analysis of Protein Disorder in Camelus dromedarius 

### ISSUE THREAD

**Issue by bioinfo2016** [kacst-bioinfo-lab/labwork#26]

**Comment by bioinfo2016** [comment]
-main reference paper[https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3567104/pdf/pone.0055524.pdf]
- Perform extensive analysis for disordered proteins in Camelus dromedarius. 
To Do:
- download Proteins of Human and Arabian Camel from Uniprot.

**Comment by Manal-Alshehri** [comment]
Dataset:

From UniProtKB, we downloaded Homo Sapiens proteins (73,947).

When searching for Camelus Dromedarius, we found a very small set of proteins. To enlarge this dataset, we decided to include other closely related organisms of camels. We adopted all Camelus genus, that include: Camelus Dromedarius, Camelus Bacterianus, and Camelus Ferus (20,745 proteins).

Since the two datasets are very large, we removed duplicated sequences by applying threshold of similarity %60 (CD-HIT). That resulted in 22,168 proteins for Homo Sapiens and 18,338 for Camelus.

**Comment by Manal-Alshehri** [comment]
/Users/Manal/Desktop/KACST/Protein-Disorder/Writing/Untitled.jpg

Table 1S. Summary of intrinsic disorder metrics for Camel and Human datasets. Results shown for IUPred prediction method (short and long).

**Comment by Manal-Alshehri** [comment]
![table1-s](https://user-images.githubusercontent.com/39729156/64919569-519ff280-d7b5-11e9-95bc-13cce4ba39dd.jpg)

Table 1S. Summary of intrinsic disorder metrics for Camel and Human datasets. Results shown for IUPred prediction methods (short and long).

**Comment by Manal-Alshehri** [comment]
![figure-s1](https://user-images.githubusercontent.com/39729156/64919582-6ed4c100-d7b5-11e9-82df-347f6b4a74e7.jpg)

**Comment by Manal-Alshehri** [comment]
![figure-s2](https://user-images.githubusercontent.com/39729156/64919591-890e9f00-d7b5-11e9-9987-ea50ecf8f4ce.jpg)

**Comment by Manal-Alshehri** [comment]
![iupred-camel-long-REVIGO-results](https://user-images.githubusercontent.com/39729156/65218908-21f82f80-dac0-11e9-8002-3ca50d3974e7.jpg)

Representation of the GO ‘‘Biological Processes’’ significantly enriched in disordered proteins in Camel dataset. Disordered proteins here correspond to those with one or more ‘‘long disordered windows’’ (LDW) based on IUPred predictions. Figure adapted from REVIGO, a system for summarizing and visualizing lists of GO terms. Each rectangle represents a cluster of related terms labeled according to a representative term. Rectangles are grouped in ‘‘superclusters’’ (identified with the same color) based on SimRel semantic similarity measure.

**Comment by Manal-Alshehri** [comment]
/Users/Manal/Desktop/KACST/Protein-Disorder/Writing/table-1S-in-suplementary-with-ESpritz.jpg

**Comment by Manal-Alshehri** [comment]
![table-1S-in-suplementary-with-ESpritz](https://user-images.githubusercontent.com/39729156/66818097-766abf80-ef45-11e9-8989-2dd08686fc2a.jpg)

Table 1S with ESpritz results included. Summary of intrinsic disorder metrics for Camel and Human datasets.

**Comment by Manal-Alshehri** [comment]
![Figure-3S-my-suplementary](https://user-images.githubusercontent.com/39729156/66818728-70291300-ef46-11e9-9092-9e4024182606.jpg)

**Comment by Manal-Alshehri** [comment]
![Figure1](https://user-images.githubusercontent.com/39729156/67261411-35286180-f4a9-11e9-80a1-7863e80c6eef.jpg)
Figure 1. Overall predicted global disorder and disordered binding regions in Camelus and H. sapiens proteins. Left: percentages of disordered proteins (disordered proteins criterion: those proteins containing at least 50% disordered residues based on Disopred predictions). Right: average percentages of disordered residues involved in binding (DBRs), as predicted by Disopred.

**Comment by Manal-Alshehri** [comment]
![Figure2-A](https://user-images.githubusercontent.com/39729156/67261699-766d4100-f4aa-11e9-8a83-077845491e01.jpg)
Figure 2-A Fraction of proteins with different degrees of predicted disorder in Camel and H. sapiens. Protein disorder (as the percentage of disordered residues with respect to the sequence length) is binned into different ranges. Data based on Disopred predictions.

**Comment by Manal-Alshehri** [comment]
![Figure2-B](https://user-images.githubusercontent.com/39729156/67472940-8b88d200-f65a-11e9-9ee4-5253d8c79d37.jpg)
Figure 2-B: Fraction of proteins with different degrees of predicted disordered binding regions in Camelus and H. sapiens

**Comment by bioinfo2016** [comment]
ANCHOR will give a better insight of the disordered binding regions.

**Comment by Manal-Alshehri** [comment]
![Table1-Disopred-ANCHOR](https://user-images.githubusercontent.com/39729156/68102278-fe0f7280-fee2-11e9-83c1-f6ce04b8a3cc.jpg)

Table1: Summary of intrinsic disorder metrics for Human and Camels. Results shown for Disopred (disorder prediction) and ANCHOR (disorder binding regions, DBRs).

**Comment by Manal-Alshehri** [comment]
![Figure2-B-anchor](https://user-images.githubusercontent.com/39729156/68102865-99094c00-fee5-11e9-9781-414af2b63ef8.jpg)
Figure 2-B: Fraction of proteins with different degrees of predicted disordered binding regions in Camelus and H. sapiens (using ANCHOR)

**Comment by Manal-Alshehri** [comment]
![Figure1-with-ANCHOR](https://user-images.githubusercontent.com/39729156/68103272-20a38a80-fee7-11e9-8d27-6a119a612e94.jpg)
Figure 1. Overall predicted global disorder and disordered binding regions in Camel and H. sapiens proteins. Left: percentages of disordered proteins (disordered proteins criterion: those proteins containing at least 50% disordered residues based on Disopred predictions). Right: average percentages of disordered residues involved in binding (DBRs), as predicted by ANCHOR.

**Comment by Manal-Alshehri** [comment]
![report](https://user-images.githubusercontent.com/39729156/71443654-4eee5b00-271d-11ea-80f0-e4d317c3760a.jpg)

**Comment by Manal-Alshehri** [comment]
GO:Biological Processes terms associated with Disordered Proteins in Camel dataset was summarized and visualized using Revigo. Disordered proteins here correspond to those with one or more ‘‘long disordered Region’’ (LDR) based on DISOPRED predictions. 
![Revigo-for-disorder-Camel](https://user-images.githubusercontent.com/39729156/71443747-d936bf00-271d-11ea-8913-e877f45bb8fe.jpg)

**Comment by Manal-Alshehri** [comment]
To perform comparative analysis between H. and C:
•	I run PANNZER on: all proteins of H., all proteins in C., Disorder H., and Disorder C. I consider GO terms that has PPV 0.7 or above.
•	I detected 1993 common (shared) Go terms that are in H. AND in C. 
•	I extract common GO terms and quantify them in: all-H.-dataset, all-C.-dataset, Disorder-H., and Disorder-C.
•	I computed contingency tables for each common GO term (observed/expected values).
•	Then computed Chi-square (P-value) for all common GO.
•	I keep only GO terms where the observed disorder in C. is greater than expected. I end up with 495 GO terms.
•	I computed the average of GO terms from previous step to see the enrichment percentage of each term in both disorder datasets. I filtered the results by considering only the terms where the percentage in C. is greater than that in H. We had 495 GO terms.
•	I found that this GO terms list are exactly the same as those when I consider Observed C. > Expected C. This was done in order to verify that the eventual differences in disorder are maintained when considering only the ‘‘comparable’’ proteins, and discard that these differences might be due to biases in the GO annotations of these two genomes.
•	To conclude, these 495 GO terms are more enriched in Camel Disordered proteins than in Human Disorder proteins.

**Comment by Manal-Alshehri** [comment]
Revigo representation of Disorder proteins in Camel using GO:BP terms with PPV>0.7. The Treemap  appearance was improved using DrasticData.

![Treemap-Disorder-C](https://user-images.githubusercontent.com/39729156/71654659-0699f300-2d44-11ea-9d1a-61bcc06b226f.jpg)

The full list of the GO terms and their description (in colored boxes) and their general representative (in white boxes) is provided by Revigo as a table (in addition to other categories such as frequency and uniqueness)

**Comment by Manal-Alshehri** [comment]
Revigo representation of GO:BP terms (with PPV>0.7) that are more enriched in Camel Disordered proteins than in Human Disorder proteins. The Treemap appearance was improved using DrasticData.

![Treemap-comparative-analysis-H-C](https://user-images.githubusercontent.com/39729156/71655031-026ed500-2d46-11ea-857f-90c8efc9bab6.jpg)

The full list of the GO terms and their description (in colored boxes) and their general representative (in white boxes) is provided by Revigo as a table (in addition to other categories such as frequency and uniqueness)

**Comment by Manal-Alshehri** [comment]
Updated summary for PANNZER results after applying **> 0.7 threshold on PPV**.

![new-report-to-github-with0 7-threshold](https://user-images.githubusercontent.com/39729156/71655233-f6374780-2d46-11ea-92ad-e7e825476b39.jpg)

**Comment by Manal-Alshehri** [comment]
Revigo representation of **_Disorder proteins in Camel_** using GO:BP terms with PPV>0.7. The Treemap appearance was improved using DrasticData.

![Treemap-Disorder-C](https://user-images.githubusercontent.com/39729156/71655296-2383f580-2d47-11ea-8faf-9e97844c239b.jpg)

The full list of the GO terms and their description (in colored boxes) and their general representative (in white boxes) is provided by Revigo as a table (in addition to other categories such as frequency and uniqueness)

**Comment by Manal-Alshehri** [comment]
Revigo representation of GO:BP terms (with PPV>0.7) that are **_more enriched in Camel Disordered proteins than in Human Disorder proteins_**. The Treemap appearance was improved using DrasticData.

![Treemap-comparative-analysis-H-C](https://user-images.githubusercontent.com/39729156/71655336-4910ff00-2d47-11ea-86cb-5589b24d6d9e.jpg)

The full list of the GO terms and their description (in colored boxes) and their general representative (in white boxes) is provided by Revigo as a table (in addition to other categories such as frequency and uniqueness)

**Comment by Manal-Alshehri** [comment]
Revigo representation of GO:BP terms (with PPV>0.7) that are **_more enriched in DBR in Camel than in Human_**. The Treemap appearance was improved using DrasticData.


![Revigo-comparative-DBR-TreeMap-result](https://user-images.githubusercontent.com/39729156/72217606-64e38480-3541-11ea-854c-eedb82f66b30.jpg)


The full list of the GO terms and their description (in colored boxes) and their general representative (in white boxes) is provided by Revigo as a table (in addition to other categories such as frequency and uniqueness)
