### ISSUE TITLE
Parsing files

### ISSUE THREAD

**Issue by MManee** [kacst-bioinfo-lab/labwork#5]
the goal of these tasks is to learn different techniques to parse files!

**Comment by MManee** [comment]
- I’ve uploaded a file (2taxa_tree.fas) in your data directory: https://github.com/kacst-bioinfo-lab/labwork/tree/master/data/abdulmalek
- the file includes thousand groups of (Root, A and B) sequences in FASTA format starting from A
- root represents the Root and A and B are the children of the root sequence
- you need to parse this file to get the conserved elements (CNEs) and spacers of each sequence
- CNEs are shown as lower case letters and spacers are shown as upper case letters 
- don’t consider dash **(-)** and star **(*)** signs in this stage
- the output file should be in bed format (recommended) or text format as you wish, and should be located in your doc directory: https://github.com/kacst-bioinfo-lab/labwork/tree/master/doc/abdulmalek  
- the output file should look like this:
```
Run	CA	CB	CR	CB-CA	CA-CR	CB-CR	SA	SB	SR	SB-SA	SA-SR	SB-SR
1	.	.	.	.	.	.	.	.	.	.	.	.
.
.
.
.
1000	.	.	.	.	.	.	.	.	.	.	.	.

```
- they are 1000 groups, so you should have 1000 runs
- **CA** is the the total CNE length of A, and **CB** is the the total CNE length of B and **CR** is the the total CNE length of Root
- **SA** is the the total spacer length of A, and **SB** is the the total spacer length of B and **SR** is the the total spacer length of Root
- and finally you should print the difference between the values as shown above

**Comment by AbuMohammad** [comment]
You can file the program on [https://github.com/kacst-bioinfo-lab/labwork/blob/master/code/abdulmalek/CNS_SPACER_Counts.py](url)
and The output file on [https://github.com/kacst-bioinfo-lab/labwork/blob/master/doc/abdulmalek/CNS_SPACER_Counts.bed](url)

**Comment by AbuMohammad** [comment]
You can find the  python code for parsing a counting the CNS & spacer in [ https://github.com/kacst-bioinfo-lab/labwork/tree/master/code/abdulmalek](url)
For the output file you can find it in [ https://github.com/kacst-bioinfo-lab/labwork/tree/master/doc/abdulmalek](url)

**Comment by MManee** [comment]
- you have to check your results again
- to help you solve this issue, the first record should look like this:
```
Run	CA	CB	CR	CB-CA	CA-CR	CB-CR	SA	SB	SR	SB-SA	SA-SR	SB-SR
1	1000	1000	1000	0	0	0	1012	985	1000	12	15	27
```
- and you script should read form the input file where it is loctated (labwork/data/abdulmalek/2taxa_tree.fas) and write the output file where it should be located (labwork/doc/abdulmalek/CNS_SPACER_Counts.bed)

**Comment by AbuMohammad** [comment]
Please find the Python code at https://github.com/kacst-bioinfo-lab/labwork/tree/master/code/abdulmalek/CNS_SPACSER_1.py
For the output file please check https://github.com/kacst-bioinfo-lab/labwork/tree/master/doc/abdulmalek/CNS_SPACER_counts1.bed
@MManee

**Comment by MManee** [comment]
#### New thread is now open to have a clean version of programming tasks for Training Purposes #22 ####
